/* eslint-disable quotes */
module.exports = () => [
  "🎶He's making a list, He's checking it twice🎶",
  "🎶He's gonna find out, Who's naughty or nice🎶",
  "🎶It's beginning to look a lot like Christmas,Toys in every store🎶",
  '🎶Oh the weather outside is frightful, But the fire is so delightful🎶',
  "🎶Rudolph with your nose so bright, won't you guide my sleigh tonight🎶",
  "🎶Next year I could be just as good...,if you'd check off my Christmas list🎶",
  '🎶Hurry down the chimney tonight🎶',
  '🎶On the second day of Christmas, my true love sent to me🎶',
  'I always like the gifts I get, But how I love the gifts I give!',
  "It's not how much we give but how much love we put into giving",
  "🎶And since we've no place to go, Let it snow, let it snow, let it snow🎶",
  'Teacher says every time a bell rings, an angel gets his wings',
  'Remember this December, that love weighs more than gold',
  'Love the giver more than the gift',
  'Gifts of time and love are surely the basic ingredients of a truly merry Christmas',
  '🎶Good tidings we bring to you and your kin. We wish you a Merry Christmas and a Happy New Year🎶',
  "There'll be parties for hosting, marshmallows for toasting, and caroling out in the snow",
  "🎶Rockin' around the Christmas tree, at the Christmas party hop🎶",
];
